---
title: 'W1: Commentary #1'
toc: false
---

Due on Blackboard no later than Monday 5 January.

Write a critical response of approximately 1,000 words (4 pages, double-spaced), responding to any of the course readings assigned this week.

Please note that this is a response paper, not a formal critical analysis paper, so it doesn't have to elaborate a specific argument, although you're certainly welcome to do that.

Think of it as your more extended commentary on what you've been reading, or a report on what it's inspired you to start exploring further (this could be a basis for your Special Topics paper at the end of the course).

Although the focus and format of the paper is informal, please be sure to use correct formatting as for a critical essay and use academic style, avoiding purely conversational writing style.

Be sure to avoid purely speculative statements about "the future of X" or whatever, that cannot be checked against any evidence or scholarship.

Some possible starting points:

- Which of these readings, or sections of them, did you find most intriguing, and why?
- Did any of them connect with your own experience using interactive media, and if so how?
- Did you try playing any of the games like [*Zork*](https://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fzdungeon.z5), which are available online via a web browser?
- Or one of the more recent apps for mobile devices like [*Frotz*]?
- Have you tried watching/playing [*Black Mirror: Bandersnatch*](https://en.wikipedia.org/wiki/Black_Mirror:_Bandersnatch)? If so, what did you make of it? 
- What do you make of the Turing Test as a model for artificial intelligence, as well as the critique of it?
- Did you try the web port of [ELIZA](https://psych.fullerton.edu/mbirnbaum/psych101/eliza.htm), the therapist chatbot described by Sherry Turkle? 